name: CI/CD para Projeto Angular (Branch develop)

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Compilar e Testar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v3  # Use a versão mais recente
        with:
          node-version: '16'

      - name: Instalar Dependências
        run: npm install

      - name: Construir o Projeto Angular
        run: npm run build

      - name: Executar Testes
        run: npm run test
