name: CI/CD para Projeto Angular (Branch develop)

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Compilar e Testar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Instalar Dependências
        run: npm install

      - name: Construir o Projeto Angular
        run: npm run build

      - name: Executar Testes
        run: npm run test

  deploy:
    name: Implantação no Servidor
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy no Servidor
        # Adicione suas etapas de implantação, como o envio dos arquivos para o servidor

  notify:
    name: Notificações
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Enviar Notificação
        # Adicione ações de notificação, como mensagens no Slack ou envio de e-mails


